from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.4.1")

##### setup singularity #####
# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"

##### load rules #####
include: "rules/common.smk"
include: "rules/preprocess.smk"
include: "rules/assembly.smk"
include: "rules/binning.smk"
include: "rules/gene_calling.smk"
include: "rules/upimapi.smk"
include: "rules/recognizer.smk"
include: "rules/metaproteomics.smk"
include: "rules/quantification.smk"
include: "rules/normalization.smk"
include: "rules/de_analysis.smk"
include: "rules/protein_report.smk"
include: "rules/entry_report.smk"
include: "rules/keggcharter.smk"
include: "rules/summary_report.smk"

##### target rules #####
rule all:
    input:
        all_input
