# This Dockerfile should only be used for testing purposes
# It differs from the main Dockerfile by including the download of MOSCARDO's files to be run with MOSCA
# Also includes the creation of a named_volume automatically, neccessary for MP spectra conversion

FROM continuumio/miniconda3

VOLUME ["named_volume"]

RUN buildDeps='build-essential zlib1g-dev' \
&& apt-get update \
&& apt-get install -y $buildDeps --no-install-recommends \
# Set up CI files
&& git clone https://github.com/iquasere/MOSCARDO.git \
&& gunzip -v MOSCARDO/input/*/mp*.RAW.gz \
&& mkdir resources_directory \
&& mv MOSCARDO/data/cdd.tar.gz MOSCARDO/data/uniprot.fasta resources_directory \
# Install MOSCA
&& git clone https://github.com/iquasere/MOSCA.git -b development \
&& bash MOSCA/install.bash --mosca_env "$(conda info --base)" \
&& conda clean --all \
&& apt-get install -y curl \
&& curl -fsSL https://get.docker.com -o get-docker.sh \
&& sh get-docker.sh \
&& apt-get purge -y --auto-remove $buildDeps

CMD [ "python", "bin/mosca.py" ]