FROM continuumio/miniconda3

RUN buildDeps='build-essential zlib1g-dev' \
&& apt-get update \
&& apt-get install -y $buildDeps --no-install-recommends \
# Set up CI files
&& git clone https://github.com/iquasere/MOSCARDO.git \
&& gunzip -v MOSCARDO/input/*/mp*.RAW.gz \
&& mkdir resources_directory \
&& mv MOSCARDO/data/cdd.tar.gz MOSCARDO/data/uniprot.fasta resources_directory \
# Install MOSCA
&& git clone https://github.com/iquasere/MOSCA.git -b development \
&& bash MOSCA/install.bash --mosca_env "$(conda info --base)" \
&& apt-get install -y packagekit-gtk3-module libasound2 libdbus-glib-1-2 libx11-xcb1 \
&& conda clean --all \
&& apt-get purge -y --auto-remove $buildDeps

CMD [ "python", "bin/mosca.py" ]