FROM continuumio/miniconda3

RUN buildDeps='build-essential zlib1g-dev' \
&& apt-get update \
&& apt-get install -y $buildDeps --no-install-recommends \
# Set up CI files
&& git clone https://github.com/iquasere/MOSCARDO.git \
&& tar -xzvf MOSCARDO/input/mp1/mp1.RAW.tar.gz -C MOSCARDO/input/mp1/ \
&& tar -xzvf MOSCARDO/input/mp2/mp2.RAW.tar.gz -C MOSCARDO/input/mp2/ \
&& tar -xzvf MOSCARDO/input/mp3/mp3.RAW.tar.gz -C MOSCARDO/input/mp3/ \
&& tar -xzvf MOSCARDO/input/mp4/mp4.RAW.tar.gz -C MOSCARDO/input/mp4/ \
&& mkdir resources_directory \
&& mv MOSCARDO/data/cdd.tar.gz MOSCARDO/data/uniprot.fasta resources_directory \
# Install MOSCA
&& git clone https://github.com/iquasere/MOSCA.git \
&& conda install -c conda-forge -y mamba \
&& mamba env update --file MOSCA/workflow/envs/base_environment.yml --name base \
&& bash MOSCA/workflow/envs/ci_build.sh \
&& conda clean --all \
&& apt-get purge -y --auto-remove $buildDeps

CMD [ "python", "bin/mosca.py" ]